# =====================================================================
# 1. GLOBAL CONFIGURATION (Must be at the very top of the file)
# =====================================================================
[config]
mode = "dark"
type = "scheme-tonal-spot"

[config.custom_colors]
red     = { color = "#FF0000", blend = true }
green   = { color = "#00FF00", blend = true }
yellow  = { color = "#FFFF00", blend = true }
blue    = { color = "#0000FF", blend = true }
magenta = { color = "#FF00FF", blend = true }
cyan    = { color = "#00FFFF", blend = true }
white   = { color = "#FFFFFF", blend = true }

# =====================================================================
# 2. TEMPLATES DEFINITIONS
# =====================================================================
[templates.hyprland]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/modules/colors.lua"

[templates.neovim]
input_path = "~/.config/matugen/templates/neovim.json"
output_path = "~/.config/nvim/lua/user/colors/matugen_base16.json"
post_hook = "pkill -USR1 nvim"

[templates.quickshell]
input_path = '~/.config/matugen/templates/quickshell.json'
output_path = '~/.local/state/quickshell/generated/colors.json'

[templates.zed]
input_path = "~/.config/matugen/templates/zed-colors.json"
output_path = "~/.config/zed/themes/matugen.json"

[templates.ghostty]
input_path = '~/.config/matugen/templates/ghostty'
output_path = '~/.config/ghostty/themes/Matugen'

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors/colors.css"

[templates.rofi]
input_path = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors/vivendi.rasi"

[templates.kitty]
input_path = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/colors.conf"

[templates.gtk]
input_path = "~/.config/matugen/templates/gtk.css"
output_path = "~/.config/gtk-4.0/gtk.css"

[templates.vscode-raw]
input_path = '~/.config/matugen/templates/vscode-colors'
output_path = '~/.cache/matugen/vscode-colors'

[templates.vscode-json]
input_path = '~/.config/matugen/templates/vscode-colors.json'
output_path = '~/.cache/matugen/vscode-colors.json'

[templates.pywalfox]
input_path = '~/.config/matugen/templates/pywalfox.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'
