general {
    no_fade_in = false
    grace = 0
    disable_loading_bar = true
}

background {
    monitor =
    path = screenshot
    blur_passes = 3
    blur_size = 7
    noise = 0.0117
    contrast = 0.8916
    brightness = 0.8172
    vibrancy = 0.1696
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 300, 60
    outline_thickness = 0
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    dots_rounding = -1
    outer_color = rgb(ffb4a7)
    inner_color = rgb(1a1110)
    font_color = rgb(f1dfdb)
    fade_on_empty = true
    fade_timeout = 1000
    placeholder_text = <i>Input Password...</i>
    hide_input = false
    rounding = 20
    check_color = rgb(ffb4a7)
    fail_color = rgb(ffb4ab)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    capslock_color = -1
    numlock_color = -1
    bothlock_color = -1
    invert_numlock = false
    swap_font_color = false
    position = 0, -50
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    color = rgba(f1dfdb, 1.0)
    font_size = 64
    font_family = Noto Sans
    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:1000] echo "$(date +'%A, %B %d')"
    color = rgba(f1dfdb, 0.8)
    font_size = 20
    font_family = Noto Sans
    position = 0, 40
    halign = center
    valign = center
}
