[config]

[templates]
[templates.hypr]
input_path = "~/.config/noctalia/templates/hypr.lua"
output_path = "~/.config/hypr/noctalia.lua"
[templates.discord_system24_vesktop]
input_path = "~/.config/noctalia/templates/discord-system24.css"
output_path = "~/.config/vesktop/themes/discord-system24.css"
# User-defined templates
# Add your custom templates below
# Example:
# [templates.myapp]
# input_path = "~/.config/noctalia/templates/myapp.css"
# output_path = "~/.config/myapp/theme.css"
# post_hook = "myapp --reload-theme"

# Remove this section and add your own templates
#[templates.placeholder]
#input_path = "/etc/xdg/quickshell/noctalia-shell/Assets/Templates/noctalia.json"
#output_path = "/home/joseph/.cache/noctalia/placeholder.json"

