foreground            #cdd6f4
background            #1e1e2e
selection_foreground  #1e1e2e
selection_background  #89b4fa
cursor                #cdd6f4
url_color             #89b4fa

color0   #1e1e2e
color8   #1e1e2e
color1   #f38ba8
color9   #f38ba8
color2   #a6e3a1
color10  #a6e3a1
color3   #f9e2af
color11  #f9e2af
color4   #89b4fa
color12  #89b4fa
color5   #cba6f7
color13  #cba6f7
color6   #94e2d5
color14  #94e2d5
color7   #cdd6f4
color15  #cdd6f4
