foreground #dee3e5
background #0f1416
selection_foreground #0f1416
selection_background #84d2e6
cursor #dee3e5
url_color #84d2e6

color0   #0f1416
color8   #0f1416
color1   #ffb4ab
color9   #ffb4ab
color2   #bec4eb
color10  #bec4eb
color3   #b2cbd2
color11  #b2cbd2
color4   #84d2e6
color12  #84d2e6
color5   #bec4eb
color13  #bec4eb
color6   #899295
color14  #899295
color7   #dee3e5
color15  #dee3e5
