foreground            #f1dfdb
background            #1a1110
selection_foreground  #1a1110
selection_background  #ffb4a7
cursor                #f1dfdb
url_color             #ffb4a7

color0   #1a1110
color8   #1a1110
color1   #ffb4ab
color9   #ffb4ab
color2   #ddc48c
color10  #ddc48c
color3   #e7bdb5
color11  #e7bdb5
color4   #ffb4a7
color12  #ffb4a7
color5   #ddc48c
color13  #ddc48c
color6   #e7bdb5
color14  #e7bdb5
color7   #f1dfdb
color15  #f1dfdb
